<?php
$line=str_replace("msgtype=","a=",$line);
$line=str_replace("ver=","b=",$line);
$line=str_replace("fix=","c=",$line);
$line=str_replace("lat=","d=",$line);
$line=str_replace("lng=","e=",$line);
$line=str_replace("speed=","f=",$line);
$line=str_replace("sts=","g=",$line);
$line=str_replace("datetime=","h=",$line);
$line=str_replace("io1=","i=",$line);
$line=str_replace("io2=","j=",$line);
$line=str_replace("io3=","k=",$line);
$line=str_replace("io4=","l=",$line);
$line=str_replace("io5=","m=",$line);
$line=str_replace("io6=","n=",$line);
$line=str_replace("io7=","o=",$line);
$line=str_replace("io8=","p=",$line);
$line=str_replace("sig_str=","q=",$line);
$line=str_replace("sup_v=","r=",$line);
?>